version: '3.4'

services:
  mssql-server:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "MyPass@word"
    ports:
       - "1433:1433"
  lms_api:
    image: ${DOCKER_REGISTRY-}lmsapi
    build:
      context: .
      dockerfile: LMS_Api/Dockerfile
    environment:
      DbServer: "mssql-server"
      DbPort: "1433"
      DbUser: "sa"
      Password: "MyPass@word"
      Database: "LmsDb"
    ports:
      - "8090:80"
    depends_on:
      - mssql-server
